name: Kernel-Auto-Release

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID'
        required: true
        default: 'HEAD'
      version_number:
        description: 'Version Number (Ex. 10.4.0)'
        required: true
        default: '10.4.0'             

jobs:
  release-packager:
    name: Release Packager
    runs-on: ubuntu-latest
    steps:
      # Install python 3
      - name: Tool Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
          architecture:   x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Currently FreeRTOS/.github/scripts houses the release script. Download it for upcoming usage
      - name: Checkout FreeRTOS Release Tools
        uses: actions/checkout@v2
        with:
          repository: FreeRTOS/FreeRTOS
          path: tools
      
      # Simpler git auth if we use checkout action and forward the repo to release script 
      - name: Checkout FreeRTOS Kernel
        uses: actions/checkout@v2
        with: 
          path: local_kernel
          fetch-depth: 0

      - name: Release
        run: |
          # Configure repo for push
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          
          # Install deps and run
          pip install -r ./tools/.github/scripts/release-requirements.txt
          ./tools/.github/scripts/release.py FreeRTOS --kernel-repo-path=local_kernel --kernel-commit=${{ github.event.inputs.commit_id }} --new-kernel-version=${{ github.event.inputs.version_number }}
          exit $?
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
